# NumPy Exercise
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.
- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

Using only NumPy, perform the following.

1. Create an array of the form $b = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$
1. Create a 2x2 array of the form $X = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$
1. Multiply the two arrays element wise, then using matrix multiplication, and finally the inner product of $b \bullet b$.
1. For each of your results in part (3), print the shape and data type.
1. Reshape (or flatten), the array $X$ such that it consists of only 1 row.
1. Create an array of the integers 1 to 10, inclusive, setting the datatype to float.
1. Create a 10x10 identity matrix using the built in numpy function.
1. Create a 10x10 identity matrix using a for loop.

In [1]:
import numpy as np

In [2]:
# 1.
b = np.array([1,2])
b

array([1, 2])

In [3]:
# 2.
X = np.array([[1, 3], [2, 4]])
X

array([[1, 3],
       [2, 4]])

In [4]:
# 3.
y1 = b * X # element wise
print(y1)


[[1 6]
 [2 8]]


In [5]:
y2 = np.matmul(b, X) # matrix multiplication
print(y2)

[ 5 11]


In [6]:
y3 = np.inner(b, b) # inner product
print( y3)

5


In [7]:
# 4. 
print(y1.shape, y1.dtype)
print(y2.shape, y2.dtype)
print(y3.shape, y3.dtype)

(2, 2) int64
(2,) int64
() int64


In [8]:
# 5.
X.shape = (1,4)
print(X)

[[1 3 2 4]]


In [9]:
# 6.
a = np.array(np.arange(1,11, dtype="float"))
a

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [10]:
# 7.
i = np.identity(10)
print(i)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [11]:
# 8:
i0 = np.array(np.zeros(100, dtype = "float"))
i0.shape = (10,10)
for r in range((len(i0))):
    for c in range((len(i0))):
        if r == c:
            i0[r, c] = 1
print(i0)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [12]:
# 8. also
I = []
for i in np.arange(10):
    row = []
    for j in np.arange(10):
        if i == j:
            row.append(1.0)
        else:
            row.append(0.0)
    I.append(row)
I = np.array(I)
I.shape = (10, 10)
print(I)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


1. (9.) Generate a set of random data, $X$, drawn from a normal distribution, consisting of 9 columns of 100 rows each, then attach a column of all ones, resulting in a 100x10 matrix for $X$.  Next generate a random array $\beta$, drawn from a uniform distribution, of length 10.  Also make an array, $\epsilon$ of length 100, drawn from a normal distribution.  Finally, compute a **vector (i.e. 1d)**  $\vec{y}$ such that $\vec{y} = X\beta + \epsilon$.  Be sure to set the random seed to 0 before drawing any random numbers.  All random numbers should be on the interval [0, 1).
1. (10.) Using the **vector** $\vec{y}$ computed in part 9, create a **vector** $\vec{c}$ containing the labels "positive" or "negative" for each value in $\vec{y}$, treating 0 as positive.  **Bonus:** Do it with a one-liner.
1. (11.) Using the classes generated in part 10, separate the **matrix X** into two smaller matricies, $X_p$, $X_n$, containing only rows which map (based on $\vec{c}$) to positive or negative values (of $\vec{y}$) respectively.


In [13]:
# 1.(9.)
np.random.seed(0)
X = np.concatenate((np.ones((100,1)), np.random.randn(100,9)), axis=1) 
B = np.random.rand(10)
e = np.random.randn(100) 
# since we used np to generate these, they will all be ndarrays
print(type(X), X.shape, type(B), B.shape, type(e), e.shape)

y = np.matmul(X,B) + e
print(type(y), y.shape) #y is also thus a ndarray, but one dim vector
print(y)

<class 'numpy.ndarray'> (100, 10) <class 'numpy.ndarray'> (10,) <class 'numpy.ndarray'> (100,)
<class 'numpy.ndarray'> (100,)
[ 4.50742931  2.7953309   2.50990382  0.72711353 -0.55795377 -3.6852123
  0.91223289 -3.8475753  -1.74887896  4.4354175   3.9086895   0.67211075
  6.54791529  2.32929016  0.0765048   2.83915352  5.40276156  0.57102897
  2.65093747  1.3110547  -4.71444164  2.25115561  3.18233489  2.25998565
  2.12886726 -1.37191333 -1.13572294 -1.76959282 -1.17168521 -1.96574839
 -0.78974907  4.47291802  0.77965817 -0.67518938 -1.00617165  0.71752483
  3.43862788  2.00563305  0.0833862  -1.9233482   1.87655674  2.49658476
 -0.91693802 -1.23425965  1.58451936  0.91921655  5.89773814  0.08330009
  3.00867436  0.12093446  1.5061099   0.19010558  3.07068766 -1.06929085
  4.71524531  1.37959766  0.85658077  2.12660989 -3.22830256 -0.1433495
  1.46923122  2.20561872 -0.7246426   3.50911064 -1.14312604  1.0670432
 -0.53785087 -0.47112064  4.85863097  1.36347532 -0.27997184  1.72962232
 

In [14]:
# 2. (10.) 
#one-liner I did, creates ndarray 1d
c = np.where(y < 0, "negative", "positive")

#alternate one-liner from solution; note c here is short for "class" NB: a list, not ndarray
#c = ["positive" if val >= 0 else "negative" for val in y]

# long-form
#c =[]
#for val in y:
#    if val >=0:
#        c.append("positive")
#    else:
#        c.append("negative")

print(type(c))
print(c)
print(X.shape, c.shape)

<class 'numpy.ndarray'>
['positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'positive' 'negative' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'negative' 'negative' 'negative' 'negative' 'negative'
 'negative' 'positive' 'positive' 'negative' 'negative' 'positive'
 'positive' 'positive' 'positive' 'negative' 'positive' 'positive'
 'negative' 'negative' 'positive' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'positive' 'positive' 'negative'
 'positive' 'positive' 'positive' 'positive' 'negative' 'negative'
 'positive' 'positive' 'negative' 'positive' 'negative' 'positive'
 'negative' 'negative' 'positive' 'positive' 'negative' 'positive'
 'negative' 'negative' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'negative' 'positive' 'positive' 'positive'
 'positive' 'positive' 'positive' 'neg

In [15]:
# 3. (11.) 
# no need to convert to ndarray in my solution, already is
# c = np.array(c) 

# there are 100 rows in X, 100 values in c; this boolean indexing, will allocate an entire row of X based on a
# value of c as we iterate across it
Xp = X[c == "positive"] 
Xn = X[c == "negative"]

print(Xp.shape, Xn.shape)
print(X[0:10,])
print(c[0:10])
print(Xp[0:10,])

(67, 10) (33, 10)
[[ 1.          1.76405235  0.40015721  0.97873798  2.2408932   1.86755799
  -0.97727788  0.95008842 -0.15135721 -0.10321885]
 [ 1.          0.4105985   0.14404357  1.45427351  0.76103773  0.12167502
   0.44386323  0.33367433  1.49407907 -0.20515826]
 [ 1.          0.3130677  -0.85409574 -2.55298982  0.6536186   0.8644362
  -0.74216502  2.26975462 -1.45436567  0.04575852]
 [ 1.         -0.18718385  1.53277921  1.46935877  0.15494743  0.37816252
  -0.88778575 -1.98079647 -0.34791215  0.15634897]
 [ 1.          1.23029068  1.20237985 -0.38732682 -0.30230275 -1.04855297
  -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [ 1.         -0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028
  -0.89546656  0.3869025  -0.51080514 -1.18063218]
 [ 1.         -0.02818223  0.42833187  0.06651722  0.3024719  -0.63432209
  -0.36274117 -0.67246045 -0.35955316 -0.81314628]
 [ 1.         -1.7262826   0.17742614 -0.40178094 -1.63019835  0.46278226
  -0.90729836  0.0519454   0.72909

1. (12.) Generate a meshgrid on the interval [0, 1], of shape 100x100.  Then compute the Euclidean Distance given by $d = \sqrt{x^2 + y^2}$ from the origin for each unit, $(x_n, y_n)$, in the grid.  **Bonus:** Do it with a one-liner.
1. (13.) Generate a set of 100 values, $p$,  on the interval $[0, 2\pi]$ and two vectors, $\vec{x}, \vec{y}$ such that $\vec{x} = cos(p)$ and $\vec{y} = sin(p)$.  Then compute the vector $\vec{r} = \sqrt{x^2 + y^2}$.  Comment on your results.

In [16]:
# 1. (12.)

import numpy as np
x_coords = np.linspace(0, 1, 100)  # [0, 0.01, .0.2, ..., 0.99]
y_coords = np.linspace(0, 1, 100)
# [0, 0.01, .0.2, ..., 0.99]
X, Y = np.meshgrid(x_coords, y_coords)
d = np.sqrt(X**2 + Y**2)
print(type(d), d.shape)
d

<class 'numpy.ndarray'> (100, 100)


array([[ 0.        ,  0.01010101,  0.02020202, ...,  0.97979798,
         0.98989899,  1.        ],
       [ 0.01010101,  0.01428499,  0.02258655, ...,  0.97985005,
         0.98995052,  1.00005101],
       [ 0.02020202,  0.02258655,  0.02856997, ...,  0.98000623,
         0.99010511,  1.00020404],
       ..., 
       [ 0.97979798,  0.97985005,  0.98000623, ...,  1.38564359,
         1.3928044 ,  1.40000146],
       [ 0.98989899,  0.98995052,  0.99010511, ...,  1.3928044 ,
         1.39992858,  1.4070892 ],
       [ 1.        ,  1.00005101,  1.00020404, ...,  1.40000146,
         1.4070892 ,  1.41421356]])

In [17]:
# 1. (12.) video soln
xx, yy = np.meshgrid(np.linspace(0, 1, 100), np.linspace(0, 1, 100))
d = [np.sqrt(xx[i, j]**2 + yy[i, j]**2) for i in range(100) for j in range(100)]
print(type(d))
d = np.array(d)
d

<class 'list'>


array([ 0.        ,  0.01010101,  0.02020202, ...,  1.40000146,
        1.4070892 ,  1.41421356])

In [18]:
# 1. (13.)
p = np.linspace(0, 2 * np.pi, 100)
x, y = np.cos(p), np.sin(p)
r = np.sqrt(x**2 + y**2)
print(type(r))
r = np.array(r)
r

<class 'numpy.ndarray'>


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

1. (14.) Generate two lists, `a`, `b`, consisting of 10 randomly drawn values from a normal and uniform distribution respectively.  Compute the mean and median of each.
1. (15.) Using `a` from part 14, create a new list `c` by calling `a = c`.  Now change the shape of `c`.  Comment on your results.
1. (16.) How would you solve the problem that appeared in part 15?

In [19]:
# 1. (14.)
a = np.random.randn(10)
b = np.random.rand(10)
print("mean of a:", a.mean())
print("median of a: ", np.median(a))
print("mean of b: ", b.mean())
print("median of b: ", np.median(b))


mean of a: -0.0386798287018
median of a:  0.0561175985453
mean of b:  0.556127786663
median of b:  0.60935027913


In [20]:
# 2 (15.)
c = a
c - a
# if arrays are identical then output will be zero's...

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
c.shape = (5,2)
a.shape # shape of a changes when c shape changes

(5, 2)

In [22]:
# 3. (16.)
a = np.random.randn(10) #regenerate a again
c = a.copy() # copy breaks the link between the objects
c.shape = (5,2)
print(a.shape, c.shape)

(10,) (5, 2)
